<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8edb5v7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8edb5v7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8edb5v7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8edb5v7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8edb5v7\appDevDebugProjectContainer([
    'container.build_hash' => '8edb5v7',
    'container.build_id' => '79b64bb9',
    'container.build_time' => 1684206978,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8edb5v7');
