<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8rioroi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8rioroi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8rioroi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8rioroi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8rioroi\appDevDebugProjectContainer([
    'container.build_hash' => '8rioroi',
    'container.build_id' => 'cf613e47',
    'container.build_time' => 1684119828,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8rioroi');
